#!/bin/sh

MKDB_DIR=/home/debian-cd/search-db/
NFS=/mnt/nfs-cdimage
OUT_DIR=${NFS}/.search-db/

/home/debian-cd/debian-cd-search/update-lists-db.pl $@

cd ${MKDB_DIR}
update_trace=0
for file in *.db; do
    if [ $file -nt trace ] ; then
	update_trace=1
    fi
done

rsync -trpx --delete ${MKDB_DIR} ${OUT_DIR}
if [ $update_trace = 1 ] ; then
    date -u > trace
    cp trace ${OUT_DIR}
fi

CURRENT_VER=$(readlink ${NFS}/release/current)
if [ "${NFS}"x != ""x ] ; then
    echo "The most recent release of Debian, currently <strong>${CURRENT_VER}</strong>" > ${OUT_DIR}/release.text
fi
